
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-tekton-quay
  title: Quarkus + Tekton + Quay
  description: Template Quarkus com build e push de imagem no Quay usando Tekton
  tags:
    - quarkus
    - java
    - tekton
    - quay
spec:
  owner: group:default/rhdh
  type: service

  parameters:
    - title: Application Info
      required:
        - repoName
        - owner
        - namespace
        - image
      properties:
        repoName:
          title: Repository Name
          type: string
        description:
          title: Description
          type: string
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
        namespace:
          title: OpenShift Namespace
          type: string
          default: quarkus
        image:
          title: Quay Image
          type: string
          default: quay.io/quayadmin/quarkus-demo
  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: github.com?owner=teste&repo=${{ parameters.repoName }}
        description: ${{ parameters.description }}
        defaultBranch: main

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
