
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-build
spec:
  params:
    - name: IMAGE
      type: string
  tasks:
    - name: build-and-push
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE)
