
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      type: string
  steps:
    - name: build
      image: quay.io/buildah/stable
      securityContext:
        privileged: true
      script: |
        buildah bud -t $(params.IMAGE) .
        buildah push $(params.IMAGE)
